const I={cover:'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80',couple:'https://images.unsplash.com/photo-1520854221256-17451cc331bf?auto=format&fit=crop&w=1200&q=80',bride:'https://images.unsplash.com/photo-1525258946800-98cfd641d0de?auto=format&fit=crop&w=900&q=80',groom:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80',story:'https://images.unsplash.com/photo-1494774157365-9e04c6720e47?auto=format&fit=crop&w=1200&q=80',poster:'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=900&q=80',hotel:'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=80'};
let state={page:'home',mode:'couple',groom:'陆一辰',bride:'林知夏',date:'2026年10月18日 星期日 17:30',hotel:'杭州湖畔白鹭酒店 · 湖景宴会厅',invite:'诚邀你见证我们人生中最温柔的一次奔赴。',story:'我们相识于一场迟到的春雨，从一起撑伞到一起规划未来。那些平凡日子里的晚风、咖啡和散步，都慢慢变成了想与你共度一生的答案。',guests:[],wishes:[],photos:{}};
const titles={mode:'选择制作方式',upload:'上传照片',identity:'确认人物身份',style:'选择婚礼风格',progress:'AI 生成中',result:'婚礼视觉包',info:'填写婚礼信息',story:'爱情故事',invite:'请帖预览',rsvp:'宾客回执',wishes:'祝福留言',admin:'项目管理'};
const $=s=>document.querySelector(s), nav=p=>{state.page=p;scrollTo(0,0);render()};
function top(){return state.page==='home'?'':`<div class="top"><button onclick="nav('home')">←</button><b>${titles[state.page]}</b><button onclick="nav('admin')">☰</button></div>`}
function hero(src,inner){return `<div class="heroImg" style="background-image:linear-gradient(180deg,rgba(36,27,24,.08),rgba(36,27,24,.52)),url(${src})">${inner}</div>`}
function home(){return `${hero(I.cover,`<span class="pill">AI Wedding Visual Studio</span><h1>几张照片，生成属于你们的整套婚礼视觉</h1><p>上传婚纱照，或者上传两个人的普通照片，自动生成婚礼合照、请帖封面、爱情故事配图和朋友圈邀请海报。</p>`)}<div class="content"><button class="primary" onclick="nav('mode')">开始制作</button><button class="secondary" onclick="nav('invite')">查看示例</button><div class="grid"><div><b>✦ 不是模板编辑器</b><p>围绕新人照片自动延展统一视觉。</p></div><div><b>◌ 两种照片入口</b><p>婚纱照优选，或普通照片生成合照。</p></div></div></div>`}
function mode(){return `<div class="content"><h2>你想从哪种照片开始？</h2>${[['wedding','上传已有婚纱照','自动挑选适合封面、故事和海报的照片。'],['couple','上传两个人普通照片','模拟生成统一风格婚礼合照与视觉包。']].map(x=>`<button class="choice" onclick="state.mode='${x[0]}';nav('upload')"><span><b>${x[1]}</b><small>${x[2]}</small></span><i>›</i></button>`).join('')}</div>`}
function uploadBox(key,label){return `<div class="upload"><input id="f-${key}" type="file" accept="image/*" onchange="pick('${key}',this)"><div class="preview" onclick="$('#f-${key}').click()">${state.photos[key]?`<img src="${state.photos[key]}">`:`<span class="plus">＋</span><span>${label}</span>`}</div>${state.photos[key]?`<button class="ghost" onclick="state.photos['${key}']='';render()">删除并重选</button>`:''}</div>`}
function pick(key,input){const f=input.files[0];if(f){state.photos[key]=URL.createObjectURL(f);render()}}
function upload(){return `<div class="content"><h2>${state.mode==='wedding'?'上传婚纱照':'分别上传新郎、新娘照片'}</h2><p class="muted">原型使用本地预览，不会上传到服务器。</p>${state.mode==='wedding'?uploadBox('wedding','选择婚纱照'):uploadBox('groom','新郎个人照')+uploadBox('bride','新娘个人照')}<div class="bottom"><button class="primary" onclick="nav('identity')">下一步：确认身份</button></div></div>`}
function identity(){return `<div class="content"><h2>确认新人信息</h2><div class="people"><img src="${state.photos.groom||I.groom}"><img src="${state.photos.bride||I.bride}"></div><input value="${state.groom}" oninput="state.groom=this.value"><input value="${state.bride}" oninput="state.bride=this.value"><div class="bottom"><button class="primary" onclick="nav('style')">选择风格</button></div></div>`}
function style(){return `<div class="content"><h2>选择视觉风格</h2>${['暖白纪实','湖畔胶片','法式花园','极简杂志'].map((s,i)=>`<button class="style" onclick="nav('progress')"><img src="${[I.couple,I.story,I.poster,I.hotel][i]}"><b>${s}</b><span>✓</span></button>`).join('')}</div>`}
function progress(){return `<div class="content center"><div class="spark">✦</div><h2>正在生成你们的婚礼视觉包</h2>${['分析人物与照片光线','生成双人主视觉','延展请帖封面与海报','整理微信分享素材'].map(s=>`<p class="step">✓ ${s}</p>`).join('')}<button class="primary" onclick="nav('result')">查看生成结果</button></div>`}
function result(){let items=['婚礼H5首屏封面','新人双人主视觉','爱情故事配图','朋友圈竖版邀请海报','微信分享封面','婚礼倒计时海报'];return `<div class="content"><h2>已生成 6 组视觉素材</h2><div class="assets">${items.map((it,i)=>`<div><img src="${[I.cover,I.couple,I.story,I.poster,I.couple,I.hotel][i]}"><b>${it}</b></div>`).join('')}</div><div class="bottom"><button class="primary" onclick="nav('info')">继续填写请帖</button></div></div>`}
function info(){return `<div class="content"><h2>婚礼信息</h2><textarea oninput="state.date=this.value">${state.date}</textarea><textarea oninput="state.hotel=this.value">${state.hotel}</textarea><textarea oninput="state.invite=this.value">${state.invite}</textarea><div class="bottom"><button class="primary" onclick="nav('story')">填写爱情故事</button></div></div>`}
function story(){return `<div class="content"><h2>爱情故事</h2><textarea class="big" oninput="state.story=this.value">${state.story}</textarea><button class="secondary" onclick="state.story+=' AI 已将故事润色为更适合请帖的温柔语气。';render()">AI 润色生成</button><div class="bottom"><button class="primary" onclick="nav('invite')">预览请帖</button></div></div>`}
function invite(){return `${hero(I.couple,`<h1>${state.groom} & ${state.bride}</h1><p>${state.date}</p>`)}<div class="content"><h2>${state.invite}</h2><p>${state.story}</p><img class="wide" src="${I.story}"><h3>⌖ ${state.hotel}</h3><button class="secondary">地图导航</button><button class="primary" onclick="nav('rsvp')">宾客回执入口</button><button class="secondary" onclick="nav('wishes')">祝福留言入口</button><button class="ghost" onclick="nav('admin')">进入新人项目管理后台</button></div>`}
function rsvp(){return `<div class="content"><h2>宾客回执</h2><input id="guest" placeholder="你的姓名"><button class="primary" onclick="state.guests.push($('#guest').value||'一位好友');nav('invite')">确认参加</button></div>`}
function wishes(){return `<div class="content"><h2>留下祝福</h2><textarea id="wish" placeholder="写给新人的祝福"></textarea><button class="primary" onclick="state.wishes.push($('#wish').value||'新婚快乐，永远幸福！');nav('invite')">提交祝福</button></div>`}
function admin(){return `<div class="content"><h2>新人项目管理后台</h2><div class="panel"><b>请帖状态</b><p>视觉包已生成 · 请帖可分享</p><p>回执 ${state.guests.length} 人 · 祝福 ${state.wishes.length} 条</p></div><button class="primary" onclick="nav('invite')">预览请帖</button><button class="secondary" onclick="nav('result')">查看视觉包</button></div>`}
function render(){app.innerHTML=top()+({home,mode,upload,identity,style,progress,result,info,story,invite,rsvp,wishes,admin}[state.page]())}
render();
